spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/music?currentSchema=music}
    username: ${POSTGRES_DB_USERNAME:root}
    password: ${POSTGRES_DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration # 기본값

  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      username: qwer
      password: 1234
      uri: mongodb://127.0.0.1:27017/mongo-db
      authentication-database: admin

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    credentials:
      accessKey: AKIAQRFLMDXLWPSFAYWW
      secretKey: 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
    s3:
      bucket: music-yoehadu

    region:
      static: ap-northeast-2
    stack:
      auto: false


jwt:
  public:
    key: classpath:/key/app.pub
  private:
    key: classpath:/key/app.key

server:
  port: 8080