server:
  port: 8080

spring:
  config:
    import:
    - app/cors/cors.yml
    - app/time/time.yml # classpath:/app/time/time.yml
    - app/jasypt/jasypt.yml

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://music-postgresql.crbsgynxozh6.ap-northeast-2.rds.amazonaws.com:5432/postgres}
    username: ${POSTGRES_DB_USERNAME:yoehadu}
    password: ${POSTGRES_DB_PASSWORD:music753951}
    driver-class-name: org.postgresql.Driver

    hikari:
    connection-timeout: 10000
    idle-timeout: 10000
    validation-timeout: 10000
    max-lifetime: 580000

  jpa:
    hibernate:
    ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration # 기본값

