spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/music?currentSchema=member}
    username: ${POSTGRES_DB_USERNAME:yoehadu}
    password: ${POSTGRES_DB_PASSWORD:music753951}
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 10000
      idle-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 580000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration # 기본값

server:
  port: 8080