spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/music?currentSchema=music}
    username: ${POSTGRES_DB_USERNAME:yoehadu}
    password: ${POSTGRES_DB_PASSWORD:music753951}
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 10000
      idle-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 580000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration # 기본값

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    credentials:
      accessKey: AKIAQRFLMDXLWPSFAYWW
      secretKey: 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
    s3:
      bucket: music-yoehadu

    region:
      static: ap-northeast-2
    stack:
      auto: false


jwt:
  secret: VyCPKM1jTTYDtVBkQmy8lPlWdQYs4NAQDiHSDWoZIqs

server:
  port: 8080